window.state = {
  myId: crypto.randomUUID(),
  myName: '',
  room: '',
  password: '',
  peers: new Map(),
  localStream: null,
  screenStream: null,
  processedStream: null,
  audioCtx: null,
  remoteAudioCtx: null,
  rnnoiseFilterNode: null,
  rnnoiseActive: false,
  rnnoiseStatus: 'off',
  audioSetupGeneration: 0,
  noiseSuppressionApplyPromise: null,
  // micEnabled = EFEKTİF mikrofon durumu (diğer kodun okuduğu). selfMicOn =
  // kullanıcının KENDİ tercihi. Efektif = selfMicOn && !serverMuted. Kurucu
  // susturması kalkınca kullanıcının kendi tercihi geri uygulanır (iki değişken).
  micEnabled: true,
  selfMicOn: true,
  serverMuted: false,
  deafened: false,
  isSharing: false,
  isRecording: false,
  recordingStream: null,
  recorder: null,
  recordedChunks: [],
  recStart: 0,
  pttMode: false,
  friendId: '',
  friends: {},
  friendRequests: [],
  globalMqtt: null,
  pttActive: false,
  volume: 1.0,
  useAI: true,
  activeControl: null,
  pendingControlReq: null,
  speakingPeers: new Map(),
  analyser: null,
  gainNode: null,
  cryptoKey: null,
  wbContext: null,
  drawing: false,
  micThreshold: 3,
  dms: {},
  activeDM: null,
  myAvatar: null,
  myAvatarHash: null,
  act: { wt: false, uno: false },
  wt: { player: null, isReady: false, lastAction: 0, ignoreNextEvent: false, joinedActivity: false },
  sb: { host: null, startedAt: 0, appliedRemoteUrl: '', remoteNavTs: 0, joinedActivity: false, lastUrl: '', lastVideoState: null, lastNavTs: 0, lastVideoSyncTs: 0, remoteVideoSyncTs: 0, authorized: [], authTs: 0, lastActionTs: 0, lastRoutineSyncTs: 0 },
  uno: {
    host: null,
    players: new Map(),
    scores: {},
    maxPlayers: 4,
    started: false,
    myHand: [],
    deck: [],
    discard: [],
    turnIndex: 0,
    direction: 1,
    currentColor: '',
    turnOrder: [],
    botHands: {},
    botTimeout: null,
    joinedActivity: false,
    pendingDrawCount: 0,
    rules: {
      startCards: 7,
      kombo: false,
      stacking: false,
      jumpIn: false,
      drawUntilPlay: false,
      noBluff: false,
      noPass: false,
      noBlackLast: false,
      mirror: false,
      zeroPass: false,
      sevenSwap: false
    }
  },
  lobbies: [],
  activeLobbyId: null,
  isLobbyHost: false,
  spectating: false,
  selectedLobbyActivity: null,
  sfwMode: false,
  aiModel: null,
  gameMode: false,
  // Sunucu geneli ses bit hızı (kbps). Kurucu, sunucu oluştururken ve kurucu
  // ayarlarından değiştirebilir; tüm katılımcılara yayılır. (item 7)
  audioBitrate: 128,
  moderators: new Set(),
  // Kurucu/yetkili tarafından susturulan oyuncuların id'leri — sustur/aç
  // butonunun durumunu (toggle) belirlemek için tüm istemcilerde tutulur.
  serverMutedIds: new Set(),
  // Kurucunun kalıcı olarak yasakladığı oyuncuların id'leri; bu odaya tekrar
  // giremezler. Kurucu tarafında localStorage'a da yazılır (bkz: room bans).
  bannedIds: new Set(),
  founderId: null,
  roomName: null
};
