window.state = {
  myId: crypto.randomUUID(),
  myName: '',
  room: '',
  password: '',
  peers: new Map(),
  localStream: null,
  screenStream: null,
  processedStream: null,
  audioCtx: null,
  micEnabled: true,
  deafened: false,
  isSharing: false,
  isRecording: false,
  recordingStream: null,
  recorder: null,
  recordedChunks: [],
  recStart: 0,
  pttMode: false,
  friendId: '',
  friends: {},
  friendRequests: [],
  globalMqtt: null,
  pttActive: false,
  volume: 1.0,
  useAI: true,
  activeControl: null,
  pendingControlReq: null,
  speakingPeers: new Map(),
  analyser: null,
  gainNode: null,
  cryptoKey: null,
  wbContext: null,
  drawing: false,
  micThreshold: 20,
  dms: {},
  activeDM: null,
  myAvatar: null,
  myAvatarHash: null,
  act: { wt: false, uno: false },
  wt: { player: null, isReady: false, lastAction: 0, ignoreNextEvent: false, joinedActivity: false },
  sb: { host: null, interactive: false, ignoreNextNav: false, joinedActivity: false, lastUrl: '', lastVideoState: null },
  uno: {
    host: null,
    players: new Map(),
    scores: {},
    maxPlayers: 4,
    started: false,
    myHand: [],
    deck: [],
    discard: [],
    turnIndex: 0,
    direction: 1,
    currentColor: '',
    turnOrder: [],
    botHands: {},
    botTimeout: null,
    joinedActivity: false,
    rules: {
      startCards: 7,
      kombo: false,
      stacking: false,
      jumpIn: false,
      drawUntilPlay: false,
      noBluff: false,
      noPass: false,
      noBlackLast: false,
      mirror: false,
      zeroPass: false,
      sevenSwap: false
    }
  },
  lobbies: [],
  activeLobbyId: null,
  isLobbyHost: false,
  spectating: false,
  selectedLobbyActivity: null,
  sfwMode: false,
  aiModel: null,
  gameMode: false
};
