// Discord tarzı kabuk (sunucu rayı, DM sütunu, kullanıcı paneli), durum
// sistemi, profil kartı ve oyun etkinliği metinleri.
// renderer.js bunları I18N.tr / I18N.en'e (ve katalog dillerine İngilizce
// yedek olarak) katar; yeni metin eklerken LEGACY_TEXT_EN'e DOKUNMA — yapısal
// anahtarlar data-i18n / t() ile kullanılır.
window.TeamSyncExtraStrings = {
  tr: {
    'shell.home': 'Direkt Mesajlar',
    'shell.activeCall': 'Aktif arama',
    'shell.addServer': 'Sunucu ekle',
    'shell.searchServers': 'Sunucu keşfet',
    'shell.findChat': 'Sohbet bul ya da başlat',
    'shell.friends': 'Arkadaşlar',
    'shell.directMessages': 'DİREKT MESAJLAR',
    'shell.newDm': 'DM oluştur',
    'shell.voiceConnected': 'Ses Bağlandı',
    'shell.disconnect': 'Bağlantıyı kes',
    'shell.openCall': 'Aramaya dön',
    'shell.mute': 'Sustur',
    'shell.unmute': 'Sesi aç',
    'shell.deafen': 'Sağırlaştır',
    'shell.undeafen': 'Sağırlaştırmayı kaldır',
    'shell.userSettings': 'Kullanıcı Ayarları',
    'shell.closeDm': 'DM’yi kapat',
    'shell.noDms': 'Henüz direkt mesaj yok. Bir arkadaşına yaz!',
    'shell.quickCall': 'Hızlı Arama',
    'shell.quickCallCreate': 'Hızlı arama başlat',
    'shell.quickCallCreateDesc': 'ID ve şifreyle katılınan klasik oda kur',
    'shell.quickCallJoin': 'ID ile katıl',
    'shell.quickCallJoinDesc': 'Bir arkadaşının oda ID’siyle bağlan',
    'shell.serversSoon': 'Sunucular yakında',
    'shell.serversSoonDesc': 'Kanallar, roller ve davet bağlantılı kalıcı sunucular bir sonraki aşamada geliyor.',
    'shell.searchSoon': 'Sunucu keşfi, kalıcı sunucularla birlikte gelecek.',
    'shell.switcherPlaceholder': 'Nereye gitmek istersin?',
    'shell.switcherEmpty': 'Eşleşen sohbet yok.',
    'shell.menu': 'Menü',
    'shell.youInCall': 'Şu an bir aramadasın',
    'friends.online': 'Çevrimiçi',
    'friends.all': 'Tümü',
    'friends.pending': 'Bekleyen',
    'friends.blocked': 'Engellenen',
    'friends.addFriend': 'Arkadaş Ekle',
    'friends.search': 'Ara',
    'friends.countOnline': 'ÇEVRİMİÇİ — {n}',
    'friends.countAll': 'TÜM ARKADAŞLAR — {n}',
    'friends.countBlocked': 'ENGELLENEN — {n}',
    'friends.countPending': 'BEKLEYEN — {n}',
    'friends.emptyOnline': 'Şu an çevrimiçi arkadaşın yok. Biraz bekle, gelirler!',
    'friends.emptyAll': 'Henüz hiç arkadaşın yok.',
    'friends.emptyBlocked': 'Engellediğin kimse yok.',
    'friends.emptyPending': 'Bekleyen arkadaşlık isteği yok.',
    'friends.emptySearch': 'Bu isimde bir arkadaş bulunamadı.',
    'friends.incoming': 'Gelen arkadaşlık isteği',
    'friends.outgoing': 'Giden arkadaşlık isteği',
    'friends.accept': 'Kabul et',
    'friends.reject': 'Reddet',
    'friends.cancelRequest': 'İsteği iptal et',
    'friends.addTitle': 'ARKADAŞ EKLE',
    'friends.addLead': 'Arkadaşlarını TeamSync ID’leriyle ekleyebilirsin (KNK-...).',
    'friends.addPlaceholder': 'Arkadaşının ID’sini gir (KNK-...)',
    'friends.yourId': 'Senin ID’n',
    'friends.activeNow': 'Şimdi Aktif',
    'friends.activeNowEmpty': 'Şimdilik sessiz...',
    'friends.activeNowDesc': 'Bir arkadaşın oyun oynamaya ya da sesli sohbete başladığında burada göreceksin.',
    'friends.inVoice': 'Sesli sohbette',
    'friends.message': 'Mesaj',
    'friends.joinRoom': 'Aramasına katıl',
    'friends.errorValidId': 'Geçerli bir ID gir (kendi ID’n olamaz).',
    'friends.errorAlreadyFriend': 'Bu kişi zaten arkadaşın.',
    'friends.requestSentTo': '{id} kişisine arkadaşlık isteği gönderildi.',
    'dm.startOfHistory': 'Bu, {name} ile olan direkt mesaj geçmişinin başlangıcı.',
    'dm.noMessages': 'Henüz mesaj yok. İlk mesajı sen gönder!',
    'dm.today': 'Bugün',
    'dm.yesterday': 'Dün',
    'dm.messageTo': '@{name} kullanıcısına mesaj gönder',
    'dm.toggleProfile': 'Kullanıcı profilini göster',
    'dm.me': 'Sen',
    'call.chat': 'Sohbet',
    'call.people': 'Kişiler',
    'call.toggleChat': 'Sohbeti göster',
    'call.inviteTitle': 'Aramaya birini davet et',
    'call.inviteDesc': 'Arkadaşlarına davet gönder ya da oda ID’sini paylaş.',
    'call.alone': 'Burada yalnızsın',
    'call.live': 'CANLI',
    'status.online': 'Çevrimiçi',
    'status.idle': 'Boşta',
    'status.dnd': 'Rahatsız Etmeyin',
    'status.invisible': 'Görünmez',
    'status.offline': 'Çevrimdışı',
    'status.onlineShort': 'Aktif',
    'status.dndDesc': 'Masaüstü bildirimleri almayacaksın',
    'status.invisibleDesc': 'Çevrimdışı görüneceksin',
    'status.for15m': '15 Dakika',
    'status.for1h': '1 Saat',
    'status.for8h': '8 Saat',
    'status.for24h': '24 Saat',
    'status.for3d': '3 gün boyunca',
    'status.forever': 'Her Zaman',
    'status.until': '{time} saatine kadar',
    'status.setCustom': 'Özel durum ayarla',
    'status.editCustom': 'Özel durumu düzenle',
    'status.clearCustom': 'Özel durumu temizle',
    'status.customTitle': 'Özel durum ayarla',
    'status.customPlaceholder': 'Neler oluyor?',
    'status.customEmoji': 'Emoji',
    'status.clearAfter': 'Şu süre sonra temizle',
    'status.clear30m': '30 dakika',
    'status.clear1h': '1 saat',
    'status.clear4h': '4 saat',
    'status.clearToday': 'Bugün',
    'status.clearNever': 'Temizleme',
    'status.editProfile': 'Profili Düzenle',
    'status.copyId': 'ID’yi Kopyala',
    'status.switchAccount': 'Hesap Değiştir',
    'status.autoIdle': 'Otomatik boşta',
    'status.idleAfter': 'Şu süre hareketsiz kalınca "Boşta" ol',
    'profile.aboutMe': 'Hakkımda',
    'profile.memberSince': 'TeamSync üyesi',
    'profile.playing': 'Oynuyor',
    'profile.inVoice': 'Sesli sohbette',
    'profile.sendMessage': 'Mesaj Gönder',
    'profile.removeFriend': 'Arkadaşlıktan Çıkar',
    'profile.mute': 'Sessize Al',
    'profile.unmute': 'Sesi Aç',
    'profile.addFriend': 'Arkadaş Ekle',
    'profile.editProfile': 'Profili Düzenle',
    'profile.loading': 'Profil yükleniyor…',
    'profile.settingsNav': 'Profil',
    'profile.settingsTitle': 'Profil',
    'profile.settingsLead': 'Arkadaşlarının profil kartında gördüğü her şeyi buradan özelleştir.',
    'profile.preview': 'Önizleme',
    'profile.displayName': 'Görünen ad',
    'profile.editName': 'Düzenle',
    'profile.avatar': 'Profil fotoğrafı',
    'profile.changeAvatar': 'Fotoğrafı değiştir',
    'profile.animatedAvatar': 'Hareketli profil fotoğrafı (GIF)',
    'profile.animatedAvatarDesc': 'En fazla 2 MB. Eski sürüm kullanan arkadaşların ilk kareyi görür.',
    'profile.uploadGif': 'GIF yükle',
    'profile.remove': 'Kaldır',
    'profile.avatarColor': 'Profil rengi',
    'profile.banner': 'Profil arka planı',
    'profile.bannerDesc': 'Bir renk seç ya da resim/GIF yükle (en fazla 4 MB).',
    'profile.bannerColor': 'Arka plan rengi',
    'profile.uploadBanner': 'Resim / GIF yükle',
    'profile.frame': 'Avatar çerçevesi',
    'profile.frameNone': 'Yok',
    'profile.frameNeon': 'Neon',
    'profile.frameGold': 'Altın',
    'profile.frameRainbow': 'Gökkuşağı',
    'profile.frameFlame': 'Alev',
    'profile.frameFrost': 'Buz',
    'profile.bio': 'Hakkımda',
    'profile.bioPlaceholder': 'Kendinden biraz bahset…',
    'profile.accent': 'Vurgu rengi',
    'profile.typingVerb': 'Yazıyor efekti',
    'profile.typingVerbDesc': 'Arkadaşların sen yazarken "Lazel yazıyor..." yerine bunu görecek. Emoji kullanabilirsin.',
    'profile.typingVerbPlaceholder': 'yazıyor',
    'profile.typingPreview': '{name} {verb}...',
    'profile.unsaved': 'Dikkat — kaydedilmemiş değişikliklerin var!',
    'profile.reset': 'Sıfırla',
    'profile.saveChanges': 'Değişiklikleri Kaydet',
    'profile.saved': 'Profil kaydedildi.',
    'profile.uploadFailed': 'Yükleme başarısız. Supabase kurulumu eksik olabilir (supabase/profile_media.sql).',
    'profile.fileTooLarge': 'Dosya çok büyük.',
    'profile.gifOnly': 'Yalnızca GIF dosyası seçebilirsin.',
    'profile.imageOnly': 'Yalnızca resim dosyası seçebilirsin.',
    'activity.settingsNav': 'Oyun Etkinliği',
    'activity.settingsTitle': 'Oyun Etkinliği',
    'activity.settingsLead': 'TeamSync hangi oyunu oynadığını otomatik algılar ve arkadaşlarına süresiyle birlikte gösterir.',
    'activity.enable': 'Oynadığım oyunu durum olarak göster',
    'activity.enableDesc': 'Kapalıyken algılama tamamen durur. Yalnızca oyunun adı ve süresi paylaşılır; çalışan programların listesi bilgisayarından asla çıkmaz.',
    'activity.current': 'Şu an algılanan',
    'activity.none': 'Algılanan oyun yok',
    'activity.noneDesc': 'Steam, Epic ve popüler oyunlar otomatik tanınır. Tanınmayan bir oyunu aşağıdan ekleyebilirsin.',
    'activity.registered': 'Eklenen oyunlar',
    'activity.registeredEmpty': 'Henüz elle eklenmiş oyun yok.',
    'activity.add': 'Ekle!',
    'activity.addTitle': 'Çalışan bir programı oyun olarak ekle',
    'activity.addPick': 'Program seç…',
    'activity.addName': 'Görünecek ad',
    'activity.rescan': 'Kütüphaneyi yeniden tara',
    'activity.rescanning': 'Taranıyor…',
    'activity.rescanDone': 'Oyun kütüphanesi tarandı: {n} oyun bulundu.',
    'activity.hide': 'Gizle',
    'activity.show': 'Göster',
    'activity.removeGame': 'Kaldır',
    'activity.playingFor': '{time} süredir',
    'activity.sourceSteam': 'Steam',
    'activity.sourceEpic': 'Epic Games',
    'activity.sourceKnown': 'Tanınan oyun',
    'activity.sourceCustom': 'Elle eklendi',
    'activity.unavailable': 'Oyun algılama bu sürümde kullanılamıyor.',
    'activity.playingLine': 'Oynuyor: {name}',
    'typing.default': 'yazıyor',
    'typing.more': 've {n} kişi daha',
    'emoji.matching': ':{q} ile eşleşen emojiler',
    'emoji.search': 'Emoji ara',
    'emoji.picker': 'Emoji',
    'emoji.addReaction': 'Tepki ekle',
    'dm.pending': 'Gönderiliyor — arkadaşın çevrimiçi olunca iletilecek',
    'groups.untitled': 'Adsız grup',
    'groups.memberCount': '{n} üye',
    'groups.membersCount': 'ÜYELER — {n}',
    'groups.members': 'Üye listesini göster',
    'groups.owner': 'Grup sahibi',
    'groups.kick': 'Gruptan çıkar',
    'groups.kickConfirm': '{name} gruptan çıkarılsın mı? Grup anahtarı yenilenir, yeni mesajları göremez.',
    'groups.leave': 'Gruptan ayrıl',
    'groups.leaveConfirm': '"{group}" grubundan ayrılmak istediğine emin misin? Geçmiş bu bilgisayardan silinir.',
    'groups.addMembers': 'Arkadaş ekle',
    'groups.add': 'Ekle',
    'groups.invitePending': 'Davet bekliyor (çevrimdışı ya da eski sürüm)',
    'groups.messageTo': '{name} grubuna mesaj gönder',
    'groups.startOfHistory': 'Grubun başlangıcı. Mesajlar yalnızca üyelerin bilgisayarlarında, şifreli olarak saklanır.',
    'groups.rename': 'Grubun adını değiştir',
    'groups.renameDesc': 'Tüm üyeler yeni adı görür.',
    'groups.startCall': 'Sesli arama başlat',
    'groups.join': 'Katıl',
    'groups.leaveCall': 'Ayrıl',
    'groups.decline': 'Reddet',
    'groups.callBy': '{name} aramayı başlattı',
    'groups.inCall': 'Aramada',
    'groups.ringing': '{group} grubunda arıyor…',
    'groups.joiningCall': 'Grup aramasına bağlanılıyor…',
    'groups.callGone': 'Arama bitmiş ya da kimseye ulaşılamadı.',
    'groups.leaveCurrentTitle': 'Başka bir aramadasın',
    'groups.leaveCurrentBody': 'Mevcut aramadan ayrılıp bu gruba katılmak ister misin?',
    'groups.deleteMessage': 'Mesajı sil',
    'groups.sendFailed': 'Mesaj gönderilemedi.',
    'groups.selectFriends': 'ARKADAŞLARINI SEÇ',
    'groups.selectedCount': '{n}/{max} arkadaş seçildi',
    'groups.searchFriends': 'Bir arkadaşının adını yaz',
    'groups.nameOptional': 'Grup adı (isteğe bağlı)',
    'groups.create': 'Grup DM oluştur',
    'groups.createDm': 'DM oluştur',
    'groups.creating': 'Oluşturuluyor…',
    'groups.createFailed': 'Grup oluşturulamadı.',
    'groups.noFriends': 'Henüz arkadaşın yok.',
    'groups.noMoreFriends': 'Eklenecek başka arkadaşın yok.',
    'groups.pendingInvites': '{n} arkadaşın çevrimdışı ya da eski sürümde; çevrimiçi olunca otomatik davet edilecek.',
    'groups.invitedToast': '{name} seni "{group}" grubuna ekledi.',
    'groups.removedToast': '"{group}" grubundan çıkarıldın.',
    'groups.keyChanged': '{name} kişisinin güvenlik anahtarı değişti (yeniden kurulum olabilir).',
    'groups.sysAdded': '{who}, {target} kişisini gruba ekledi.',
    'groups.sysRemoved': '{who}, {target} kişisini gruptan çıkardı.',
    'groups.sysLeft': '{who} gruptan ayrıldı.',
    'groups.sysRenamed': '{who} grubun adını "{name}" yaptı.',
    'groups.sysCall': '{who} bir arama başlattı.',
    "servers.servers": "Sunucular",
    "servers.create": "Sunucu oluştur",
    "servers.createDesc": "Kanallar, roller ve davet bağlantılarıyla kendi topluluğun",
    "servers.join": "Sunucuya katıl",
    "servers.joinDesc": "Bir davet bağlantısı ya da koduyla",
    "servers.createTitle": "Sunucunu oluştur",
    "servers.createLead": "Sunucun, sen ve arkadaşlarının takıldığı yer. Bir ad ve simge seç, sonra arkadaşlarını davet et.",
    "servers.serverName": "Sunucu adı",
    "servers.hostedNote": "Sunucu senin bilgisayarında barındırılır: sen ya da seçtiğin ortak barındırıcılar çevrimiçiyken açıktır. Hiçbiri çevrimiçi değilse sunucu gri görünür ve salt okunur olur.",
    "servers.createBtn": "Oluştur",
    "servers.creating": "Oluşturuluyor…",
    "servers.defaultName": "{name} sunucusu",
    "servers.defaultText": "genel",
    "servers.defaultVoice": "Genel",
    "servers.upload": "Yükle",
    "servers.removeIcon": "Simgeyi kaldır",
    "servers.iconError": "Bu görsel kullanılamadı. PNG, JPG ya da WEBP dene.",
    "servers.joinTitle": "Bir sunucuya katıl",
    "servers.joinLead": "Aşağıya bir davet bağlantısı ya da kodu gir.",
    "servers.inviteLink": "Davet bağlantısı",
    "servers.joinExamples": "Davetler şöyle görünür:",
    "servers.joinBtn": "Sunucuya katıl",
    "servers.joining": "Katılınıyor…",
    "servers.joinShort": "Katıl",
    "servers.joined": "Katıldın",
    "servers.open": "Aç",
    "servers.joinedToast": "\"{name}\" sunucusuna katıldın!",
    "servers.inviteBadFormat": "Bu bir TeamSync davet bağlantısına benzemiyor.",
    "servers.inviteLooking": "Sunucu aranıyor…",
    "servers.inviteNotFound": "Davet bulunamadı: süresi dolmuş olabilir ya da sunucuyu barındıran kimse şu an çevrimiçi değil.",
    "servers.inviteCardLabel": "Bir sunucuya katılmaya davet edildin",
    "servers.inviteLoading": "Davet yükleniyor…",
    "servers.inviteInvalid": "Geçersiz davet",
    "servers.inviteInvalidDesc": "Süresi dolmuş ya da sunucu şu an çevrimdışı.",
    "servers.onlineCount": "{n} çevrimiçi",
    "servers.memberCount": "{n} üye",
    "servers.inviteTitle": "Arkadaşlarını {name} sunucusuna davet et",
    "servers.searchFriends": "Arkadaş ara",
    "servers.inviteBtn": "Davet et",
    "servers.invited": "Gönderildi",
    "servers.noFriendsToInvite": "Davet edilecek arkadaş yok.",
    "servers.orSendLink": "Ya da arkadaşına bir davet bağlantısı gönder",
    "servers.creatingInvite": "Bağlantı oluşturuluyor…",
    "servers.copy": "Kopyala",
    "servers.copied": "Kopyalandı",
    "servers.editInvite": "Davet bağlantısını düzenle",
    "servers.expireAfter": "Süre sonu",
    "servers.maxUses": "Azami kullanım",
    "servers.usesN": "{n} kullanım",
    "servers.usesUnlimited": "Sınırsız",
    "servers.usesLeft": "{n} kullanım kaldı",
    "servers.generateLink": "Yeni bağlantı oluştur",
    "servers.exp1d": "1 gün",
    "servers.exp3d": "3 gün",
    "servers.exp7d": "7 gün",
    "servers.exp30d": "30 gün",
    "servers.expNever": "Süresiz",
    "servers.inviteNeverExpires": "Bu davetin süresi dolmaz.",
    "servers.inviteExpiresDays": "Davet bağlantısının süresi {n} gün sonra dolar.",
    "servers.inviteExpiresHours": "Davet bağlantısının süresi {n} saat sonra dolar.",
    "servers.invite": "Davet et",
    "servers.invitePeople": "İnsanları davet et",
    "servers.memberList": "Üye listesi",
    "servers.settings": "Sunucu ayarları",
    "servers.createChannel": "Kanal oluştur",
    "servers.createChannelBtn": "Kanal oluştur",
    "servers.editChannel": "Kanalı düzenle",
    "servers.hosting": "Barındırma",
    "servers.changeNick": "Takma adını değiştir",
    "servers.changeNickDesc": "Bu sunucudaki herkes seni bu adla görür.",
    "servers.markRead": "Okundu olarak işaretle",
    "servers.leave": "Sunucudan ayrıl",
    "servers.leaveConfirm": "\"{name}\" sunucusundan ayrılmak istediğine emin misin? Yeniden katılmak için davet gerekir.",
    "servers.deleteServer": "Sunucuyu sil",
    "servers.deleteConfirm": "\"{name}\" herkes için silinecek. Bu geri alınamaz.",
    "servers.deleteLead": "\"{name}\" sunucusunu silmek üzeresin. Tüm kanallar ve mesajlar herkesin bilgisayarından kaldırılır; bu işlem geri alınamaz.",
    "servers.typeName": "Onaylamak için sunucu adını yaz",
    "servers.textChannels": "Metin kanalları",
    "servers.voiceChannels": "Ses kanalları",
    "servers.noTextChannels": "Metin kanalı yok",
    "servers.noVoiceChannels": "Ses kanalı yok",
    "servers.live": "CANLI",
    "servers.syncing": "Sunucu bilgileri alınıyor…",
    "servers.syncingLong": "Sunucu bilgileri bir barındırıcıdan alınıyor. Barındıran kimse çevrimiçi değilse biri gelince tamamlanır.",
    "servers.noChannelsVisible": "Görebildiğin bir metin kanalı yok.",
    "servers.offlineShort": "çevrimdışı",
    "servers.offlineTitle": "Sunucu çevrimdışı",
    "servers.offlineBody": "Sunucuyu barındıran kimse şu an çevrimiçi değil. Eski mesajları okuyabilirsin ama yazamaz ve ses kanallarına giremezsin.",
    "servers.offlineComposer": "Sunucu çevrimdışı — barındıran biri gelince yazabilirsin",
    "servers.offlineVoice": "Sunucu çevrimdışı: barındıran biri çevrimiçi olunca ses kanallarına girebilirsin.",
    "servers.noConnect": "Bu ses kanalına bağlanma iznin yok.",
    "servers.noSendPerm": "Bu kanalda mesaj gönderme iznin yok",
    "servers.messageTo": "#{name} kanalına mesaj gönder",
    "servers.welcomeChannel": "#{name} kanalına hoş geldin!",
    "servers.channelStart": "Bu, #{name} kanalının başlangıcı.",
    "servers.loadOlder": "Daha eski mesajları yükle",
    "servers.reply": "Yanıtla",
    "servers.edit": "Düzenle",
    "servers.edited": "(düzenlendi)",
    "servers.editHint": "Kaydetmek için Enter · iptal için Esc",
    "servers.deletedMessage": "Silinmiş mesaj",
    "servers.deleteMessageConfirm": "Bu mesaj herkes için silinsin mi? (Sormadan silmek için Shift basılıyken tıkla.)",
    "servers.replyingTo": "{name} kişisine yanıt veriyorsun",
    "servers.slowOn": "Yavaş mod: {t}",
    "servers.slowWait": "Yavaş mod — {t} sonra yazabilirsin",
    "servers.seconds": "{n} sn",
    "servers.minutes": "{n} dk",
    "servers.hours": "{n} sa",
    "servers.slowOff": "Kapalı",
    "servers.onlineSection": "Çevrimiçi",
    "servers.offlineSection": "Çevrimdışı",
    "servers.owner": "Sunucu sahibi",
    "servers.hostBadge": "Barındırıcı: sunucu bu kişinin bilgisayarında da duruyor",
    "servers.memberSince": "Üyelik: {date}",
    "servers.roles": "Roller",
    "servers.noRoles": "Rol yok",
    "servers.addRole": "Rol ekle",
    "servers.removeRole": "Rolü kaldır",
    "servers.sendMessage": "Mesaj gönder",
    "servers.addFriend": "Arkadaş ekle",
    "servers.kick": "At",
    "servers.kickConfirm": "{name} sunucudan atılsın mı? Bir davetle geri gelebilir.",
    "servers.ban": "Yasakla",
    "servers.banConfirm": "{name} sunucudan yasaklansın mı? Yasak kaldırılana kadar geri giremez. İstersen bir sebep yaz.",
    "servers.banReason": "Sebep (isteğe bağlı)",
    "servers.bannedBy": "{name} tarafından",
    "servers.unban": "Yasağı kaldır",
    "servers.offerHost": "Barındırıcı yap",
    "servers.offerHostConfirm": "{name} kişisine ortak barındırıcılık teklif edilsin mi? Kabul ederse sunucunun tüm geçmişi onun bilgisayarında da saklanır ve sen çevrimdışıyken sunucu açık kalır.",
    "servers.offerHostSent": "{name} kişisine barındırma teklifi gönderildi.",
    "servers.hostOfferTitle": "Barındırma teklifi",
    "servers.hostOfferBody": "{name} bu sunucuyu senin bilgisayarında da barındırmanı istiyor. Kabul edersen sunucu, sahibi çevrimdışıyken de açık kalır.",
    "servers.hostOfferToast": "\"{name}\" sunucusu için bir barındırma teklifin var.",
    "servers.accept": "Kabul et",
    "servers.decline": "Reddet",
    "servers.nowHost": "Artık bu sunucunun barındırıcısısın. Geçmiş arka planda indiriliyor.",
    "servers.kickedToast": "\"{name}\" sunucusundan atıldın.",
    "servers.bannedToast": "\"{name}\" sunucusundan yasaklandın.",
    "servers.deletedToast": "\"{name}\" sunucusu silindi.",
    "servers.errOffline": "Sunucu çevrimdışı: barındıran kimse çevrimiçi değil.",
    "servers.errPerm": "Bunun için iznin yok.",
    "servers.errTimeout": "Barındırıcı yanıt vermedi. Tekrar dene.",
    "servers.errClock": "Bilgisayarının saati yanlış görünüyor; saati düzeltip tekrar dene.",
    "servers.errInvite": "Bu davetin süresi dolmuş ya da kullanım sınırına ulaşmış.",
    "servers.errBanned": "Bu sunucudan yasaklısın.",
    "servers.errNotFound": "Sunucu bulunamadı ya da şu an çevrimdışı.",
    "servers.errOwner": "Sahip sunucudan ayrılamaz; istersen sunucuyu silebilirsin.",
    "servers.errNetwork": "Bağlantı yok. Biraz sonra tekrar dene.",
    "servers.errGeneric": "Bir şeyler ters gitti.",
    "servers.channelType": "Kanal türü",
    "servers.kindText": "Metin",
    "servers.kindTextDesc": "Mesaj, emoji ve bağlantı gönder",
    "servers.kindVoice": "Ses",
    "servers.kindVoiceDesc": "Sesli konuş, ekran paylaş",
    "servers.channelName": "Kanal adı",
    "servers.newChannelPh": "yeni-kanal",
    "servers.privateChannel": "Özel kanal",
    "servers.privateChannelDesc": "Yalnızca seçtiğin roller (ve sen) görebilir.",
    "servers.privateNoRoles": "Henüz rol yok: şimdilik yalnızca sen ve yöneticiler görebilir. Sunucu ayarlarından rol oluşturabilirsin.",
    "servers.channelSettings": "Kanal ayarları",
    "servers.channelTopic": "Kanal konusu",
    "servers.slowMode": "Yavaş mod",
    "servers.slowModeDesc": "Üyeler, seçtiğin süre dolmadan yeni mesaj gönderemez (mesajları yönetebilenler hariç).",
    "servers.channelPerms": "Kanal izinleri",
    "servers.channelPermsDesc": "Her kutuya tıkla: / rolün varsayılanı, ✓ izin ver, ✕ engelle. @everyone satırı herkesi etkiler.",
    "servers.permShort.VIEW_CHANNEL": "Görüntüle",
    "servers.permShort.SEND_MESSAGES": "Yaz",
    "servers.permShort.ADD_REACTIONS": "Tepki",
    "servers.permShort.MANAGE_MESSAGES": "Yönet",
    "servers.permShort.CONNECT": "Bağlan",
    "servers.allow": "İzin verildi",
    "servers.deny": "Engellendi",
    "servers.inherit": "Varsayılan",
    "servers.remove": "Kaldır",
    "servers.addRoleOrMember": "Rol ya da üye ekle",
    "servers.moveUp": "Yukarı",
    "servers.moveDown": "Aşağı",
    "servers.deleteChannel": "Kanalı sil",
    "servers.deleteChannelConfirm": "#{name} kanalı silinsin mi?",
    "servers.save": "Değişiklikleri kaydet",
    "servers.saved": "Kaydedildi.",
    "servers.reset": "Sıfırla",
    "servers.unsaved": "Kaydedilmemiş değişikliklerin var!",
    "servers.unsavedTitle": "Kaydedilmemiş değişiklikler",
    "servers.unsavedBody": "Kaydetmeden çıkılsın mı?",
    "servers.tabOverview": "Genel bakış",
    "servers.tabRoles": "Roller",
    "servers.tabMembers": "Üyeler",
    "servers.tabInvites": "Davetler",
    "servers.tabBans": "Yasaklar",
    "servers.tabHosting": "Barındırma",
    "servers.description": "Açıklama",
    "servers.descriptionPh": "Sunucun ne hakkında?",
    "servers.publicTitle": "Sunucu Keşfet’te göster",
    "servers.publicDesc": "Herkes sunucunu bulup davetsiz katılabilir (bir barındırıcı çevrimiçiyken). Bunun için süresiz bir herkese açık davet oluşturulur.",
    "servers.rolesLead": "Roller üyelere izin ve renk verir. Üstteki rol, alttakileri yönetebilir.",
    "servers.createRole": "Rol oluştur",
    "servers.newRole": "yeni rol",
    "servers.roleName": "Rol adı",
    "servers.roleColor": "Rol rengi",
    "servers.defaultColor": "Varsayılan",
    "servers.roleHoist": "Üyeleri ayrı göster",
    "servers.roleHoistDesc": "Bu roldeki çevrimiçi üyeler üye listesinde kendi başlıkları altında görünür.",
    "servers.roleLocked": "Bu rol senin en yüksek rolünden yukarıda (ya da eşit); düzenleyemezsin.",
    "servers.everyoneDesc": "@everyone, sunucudaki herkesin varsayılan izinleridir.",
    "servers.permissions": "İzinler",
    "servers.deleteRole": "Rolü sil",
    "servers.deleteRoleConfirm": "\"{name}\" rolü silinsin mi?",
    "servers.searchMembers": "Üye ara",
    "servers.manage": "Yönet",
    "servers.invitesLead": "Etkin davet bağlantıları. Kendi davetlerini ya da (Sunucuyu Yönet izniyle) herkesinkini iptal edebilirsin.",
    "servers.createInvite": "Davet oluştur",
    "servers.inviter": "Davet eden",
    "servers.inviteCode": "Kod",
    "servers.uses": "Kullanım",
    "servers.expires": "Süre",
    "servers.revoke": "İptal et",
    "servers.noInvites": "Etkin davet yok.",
    "servers.publicPill": "Herkese açık",
    "servers.noBans": "Yasaklı kimse yok.",
    "servers.hostingLead": "Sunucu tek bir merkezde değil, barındırıcıların bilgisayarlarında durur: sahip ve sahibin teklifini kabul eden ortak barındırıcılar tüm mesaj geçmişini saklar, yeni mesajları onaylar ve kurallara (izinler, yavaş mod, yasaklar) uyulmasını sağlar. En az biri çevrimiçiyken sunucu açıktır.",
    "servers.hostingUp": "Sunucu açık — {n} barındırıcı çevrimiçi",
    "servers.hostingDown": "Sunucu kapalı — çevrimiçi barındırıcı yok",
    "servers.hostingMax": "En fazla {n} barındırıcı olabilir (sahip dahil).",
    "servers.hosts": "Barındırıcılar",
    "servers.ownerHost": "Sahip",
    "servers.coHost": "Ortak barındırıcı",
    "servers.onlineNow": "çevrimiçi",
    "servers.offlineNow": "çevrimdışı",
    "servers.removeHost": "Kaldır",
    "servers.resignHost": "Barındırmayı bırak",
    "servers.resignConfirm": "Bu sunucuyu barındırmayı bırakmak istiyor musun? Mesaj geçmişi bilgisayarında kalır ama artık sunucuyu açık tutmazsın.",
    "servers.offerPending": "Teklif bekliyor",
    "servers.cancelOffer": "Teklifi geri al",
    "servers.pickMember": "Bir üye seç…",
    "servers.thisComputer": "Bu bilgisayar",
    "servers.storageHost": "Barındırıcı olarak bu bilgisayar {n} mesajı saklıyor (yaklaşık {mb} MB).",
    "servers.storageMember": "Üye olarak yalnızca gördüğün mesajlar önbellekte tutulur ({n} mesaj).",
    "servers.discoverTitle": "Sunucu Keşfet",
    "servers.discoverLead": "Herkese açık TeamSync toplulukları. Yalnızca şu an barındırıcısı çevrimiçi olanlar listelenir.",
    "servers.discoverSearch": "Topluluk ara",
    "servers.discoverLoading": "Herkese açık sunucular aranıyor…",
    "servers.discoverEmpty": "Şu an çevrimiçi, herkese açık bir sunucu bulunamadı.",
    "servers.discoverNoMatch": "Aramana uyan sunucu yok.",
    "servers.refresh": "Yenile",
    "servers.haveInvite": "Davetim var",
    "servers.perm.VIEW_CHANNEL": "Kanalları görüntüle",
    "servers.permDesc.VIEW_CHANNEL": "Üyelerin kanalları (özel olanlar hariç) görmesini sağlar.",
    "servers.perm.SEND_MESSAGES": "Mesaj gönder",
    "servers.permDesc.SEND_MESSAGES": "Metin kanallarına mesaj yazabilir.",
    "servers.perm.ADD_REACTIONS": "Tepki ekle",
    "servers.permDesc.ADD_REACTIONS": "Mesajlara emoji tepkisi ekleyebilir.",
    "servers.perm.CONNECT": "Ses kanalına bağlan",
    "servers.permDesc.CONNECT": "Ses kanallarına girip konuşabilir.",
    "servers.perm.CREATE_INVITE": "Davet oluştur",
    "servers.permDesc.CREATE_INVITE": "Sunucuya yeni insanlar davet edebilir.",
    "servers.perm.MANAGE_MESSAGES": "Mesajları yönet",
    "servers.permDesc.MANAGE_MESSAGES": "Başkalarının mesajlarını silebilir; yavaş moddan etkilenmez.",
    "servers.perm.MANAGE_CHANNELS": "Kanalları yönet",
    "servers.permDesc.MANAGE_CHANNELS": "Kanal oluşturabilir, düzenleyebilir, silebilir ve yavaş modu ayarlayabilir.",
    "servers.perm.MANAGE_ROLES": "Rolleri yönet",
    "servers.permDesc.MANAGE_ROLES": "Kendi en yüksek rolünün altındaki rolleri düzenleyip üyelere verebilir; kanal izinlerini değiştirebilir.",
    "servers.perm.KICK_MEMBERS": "Üyeleri at",
    "servers.permDesc.KICK_MEMBERS": "Kendinden düşük roldeki üyeleri sunucudan atabilir.",
    "servers.perm.BAN_MEMBERS": "Üyeleri yasakla",
    "servers.permDesc.BAN_MEMBERS": "Kendinden düşük roldeki üyeleri yasaklayabilir ve yasak kaldırabilir.",
    "servers.perm.MANAGE_SERVER": "Sunucuyu yönet",
    "servers.permDesc.MANAGE_SERVER": "Sunucunun adını, simgesini, açıklamasını değiştirebilir; @everyone ile herkesi anabilir; tüm davetleri iptal edebilir.",
    "servers.perm.ADMINISTRATOR": "Yönetici",
    "servers.permDesc.ADMINISTRATOR": "Tüm izinler; kanal kısıtlamalarını da aşar. Dikkatli ver!",
    "servers.memberCountOne": "{n} üye",
    "servers.readOnly": "salt okunur"
  },
  en: {
    'shell.home': 'Direct Messages',
    'shell.activeCall': 'Active call',
    'shell.addServer': 'Add a server',
    'shell.searchServers': 'Discover servers',
    'shell.findChat': 'Find or start a conversation',
    'shell.friends': 'Friends',
    'shell.directMessages': 'DIRECT MESSAGES',
    'shell.newDm': 'Create DM',
    'shell.voiceConnected': 'Voice Connected',
    'shell.disconnect': 'Disconnect',
    'shell.openCall': 'Back to call',
    'shell.mute': 'Mute',
    'shell.unmute': 'Unmute',
    'shell.deafen': 'Deafen',
    'shell.undeafen': 'Undeafen',
    'shell.userSettings': 'User Settings',
    'shell.closeDm': 'Close DM',
    'shell.noDms': 'No direct messages yet. Say hi to a friend!',
    'shell.quickCall': 'Quick Call',
    'shell.quickCallCreate': 'Start a quick call',
    'shell.quickCallCreateDesc': 'Classic room joined with an ID and password',
    'shell.quickCallJoin': 'Join with an ID',
    'shell.quickCallJoinDesc': "Connect using a friend's room ID",
    'shell.serversSoon': 'Servers are coming',
    'shell.serversSoonDesc': 'Persistent servers with channels, roles and invite links arrive in the next phase.',
    'shell.searchSoon': 'Server discovery arrives together with persistent servers.',
    'shell.switcherPlaceholder': 'Where would you like to go?',
    'shell.switcherEmpty': 'No matching conversations.',
    'shell.menu': 'Menu',
    'shell.youInCall': "You're in a call",
    'friends.online': 'Online',
    'friends.all': 'All',
    'friends.pending': 'Pending',
    'friends.blocked': 'Blocked',
    'friends.addFriend': 'Add Friend',
    'friends.search': 'Search',
    'friends.countOnline': 'ONLINE — {n}',
    'friends.countAll': 'ALL FRIENDS — {n}',
    'friends.countBlocked': 'BLOCKED — {n}',
    'friends.countPending': 'PENDING — {n}',
    'friends.emptyOnline': "No one's around to play with right now.",
    'friends.emptyAll': "You don't have any friends yet.",
    'friends.emptyBlocked': "You haven't blocked anyone.",
    'friends.emptyPending': 'There are no pending friend requests.',
    'friends.emptySearch': 'No friends match that name.',
    'friends.incoming': 'Incoming friend request',
    'friends.outgoing': 'Outgoing friend request',
    'friends.accept': 'Accept',
    'friends.reject': 'Ignore',
    'friends.cancelRequest': 'Cancel request',
    'friends.addTitle': 'ADD FRIEND',
    'friends.addLead': 'You can add friends with their TeamSync ID (KNK-...).',
    'friends.addPlaceholder': "Enter your friend's ID (KNK-...)",
    'friends.yourId': 'Your ID',
    'friends.activeNow': 'Active Now',
    'friends.activeNowEmpty': "It's quiet for now...",
    'friends.activeNowDesc': 'When a friend starts playing a game or joins a voice chat, it will show up here.',
    'friends.inVoice': 'In a voice chat',
    'friends.message': 'Message',
    'friends.joinRoom': 'Join their call',
    'friends.errorValidId': "Enter a valid ID (it can't be your own).",
    'friends.errorAlreadyFriend': "You're already friends with this person.",
    'friends.requestSentTo': 'Friend request sent to {id}.',
    'dm.startOfHistory': 'This is the beginning of your direct message history with {name}.',
    'dm.noMessages': 'No messages yet. Send the first one!',
    'dm.today': 'Today',
    'dm.yesterday': 'Yesterday',
    'dm.messageTo': 'Message @{name}',
    'dm.toggleProfile': 'Show user profile',
    'dm.me': 'You',
    'call.chat': 'Chat',
    'call.people': 'People',
    'call.toggleChat': 'Show chat',
    'call.inviteTitle': 'Invite someone to the call',
    'call.inviteDesc': 'Send an invite to friends or share the room ID.',
    'call.alone': "You're alone here",
    'call.live': 'LIVE',
    'status.online': 'Online',
    'status.idle': 'Idle',
    'status.dnd': 'Do Not Disturb',
    'status.invisible': 'Invisible',
    'status.offline': 'Offline',
    'status.onlineShort': 'Online',
    'status.dndDesc': "You won't receive desktop notifications",
    'status.invisibleDesc': "You'll appear offline",
    'status.for15m': 'For 15 Minutes',
    'status.for1h': 'For 1 Hour',
    'status.for8h': 'For 8 Hours',
    'status.for24h': 'For 24 Hours',
    'status.for3d': 'For 3 Days',
    'status.forever': 'Forever',
    'status.until': 'Until {time}',
    'status.setCustom': 'Set Custom Status',
    'status.editCustom': 'Edit Custom Status',
    'status.clearCustom': 'Clear Custom Status',
    'status.customTitle': 'Set a custom status',
    'status.customPlaceholder': "What's happening?",
    'status.customEmoji': 'Emoji',
    'status.clearAfter': 'Clear after',
    'status.clear30m': '30 minutes',
    'status.clear1h': '1 hour',
    'status.clear4h': '4 hours',
    'status.clearToday': 'Today',
    'status.clearNever': "Don't clear",
    'status.editProfile': 'Edit Profile',
    'status.copyId': 'Copy ID',
    'status.switchAccount': 'Switch Account',
    'status.autoIdle': 'Automatic idle',
    'status.idleAfter': 'Become "Idle" after being inactive for',
    'profile.aboutMe': 'About Me',
    'profile.memberSince': 'TeamSync member',
    'profile.playing': 'Playing',
    'profile.inVoice': 'In a voice chat',
    'profile.sendMessage': 'Send Message',
    'profile.removeFriend': 'Remove Friend',
    'profile.mute': 'Mute',
    'profile.unmute': 'Unmute',
    'profile.addFriend': 'Add Friend',
    'profile.editProfile': 'Edit Profile',
    'profile.loading': 'Loading profile…',
    'profile.settingsNav': 'Profile',
    'profile.settingsTitle': 'Profile',
    'profile.settingsLead': "Customize everything your friends see on your profile card.",
    'profile.preview': 'Preview',
    'profile.displayName': 'Display name',
    'profile.editName': 'Edit',
    'profile.avatar': 'Avatar',
    'profile.changeAvatar': 'Change avatar',
    'profile.animatedAvatar': 'Animated avatar (GIF)',
    'profile.animatedAvatarDesc': 'Up to 2 MB. Friends on older versions see the first frame.',
    'profile.uploadGif': 'Upload GIF',
    'profile.remove': 'Remove',
    'profile.avatarColor': 'Profile color',
    'profile.banner': 'Profile banner',
    'profile.bannerDesc': 'Pick a color or upload an image/GIF (up to 4 MB).',
    'profile.bannerColor': 'Banner color',
    'profile.uploadBanner': 'Upload image / GIF',
    'profile.frame': 'Avatar frame',
    'profile.frameNone': 'None',
    'profile.frameNeon': 'Neon',
    'profile.frameGold': 'Gold',
    'profile.frameRainbow': 'Rainbow',
    'profile.frameFlame': 'Flame',
    'profile.frameFrost': 'Frost',
    'profile.bio': 'About Me',
    'profile.bioPlaceholder': 'Tell people a little about yourself…',
    'profile.accent': 'Accent color',
    'profile.typingVerb': 'Typing effect',
    'profile.typingVerbDesc': 'Friends will see this instead of "Lazel is typing..." while you type. Emoji allowed.',
    'profile.typingVerbPlaceholder': 'is typing',
    'profile.typingPreview': '{name} {verb}...',
    'profile.unsaved': 'Careful — you have unsaved changes!',
    'profile.reset': 'Reset',
    'profile.saveChanges': 'Save Changes',
    'profile.saved': 'Profile saved.',
    'profile.uploadFailed': 'Upload failed. The Supabase setup may be missing (supabase/profile_media.sql).',
    'profile.fileTooLarge': 'That file is too large.',
    'profile.gifOnly': 'Please choose a GIF file.',
    'profile.imageOnly': 'Please choose an image file.',
    'activity.settingsNav': 'Activity',
    'activity.settingsTitle': 'Game Activity',
    'activity.settingsLead': 'TeamSync detects which game you are playing and shows it to your friends with a timer.',
    'activity.enable': 'Display current activity as a status message',
    'activity.enableDesc': 'When off, detection stops completely. Only the game name and play time are shared; your list of running programs never leaves your PC.',
    'activity.current': 'Currently detected',
    'activity.none': 'No game detected',
    'activity.noneDesc': "Steam, Epic and popular games are recognized automatically. Add a game that isn't recognized below.",
    'activity.registered': 'Added games',
    'activity.registeredEmpty': 'No manually added games yet.',
    'activity.add': 'Add it!',
    'activity.addTitle': 'Add a running program as a game',
    'activity.addPick': 'Select a program…',
    'activity.addName': 'Display name',
    'activity.rescan': 'Rescan game library',
    'activity.rescanning': 'Scanning…',
    'activity.rescanDone': 'Game library scanned: {n} games found.',
    'activity.hide': 'Hide',
    'activity.show': 'Show',
    'activity.removeGame': 'Remove',
    'activity.playingFor': 'for {time}',
    'activity.sourceSteam': 'Steam',
    'activity.sourceEpic': 'Epic Games',
    'activity.sourceKnown': 'Recognized game',
    'activity.sourceCustom': 'Added manually',
    'activity.unavailable': 'Game detection is not available in this build.',
    'activity.playingLine': 'Playing {name}',
    'typing.default': 'is typing',
    'typing.more': 'and {n} more',
    'emoji.matching': 'Emoji matching :{q}',
    'emoji.search': 'Search emoji',
    'emoji.picker': 'Emoji',
    'emoji.addReaction': 'Add reaction',
    'dm.pending': "Sending — will be delivered when your friend is online",
    'groups.untitled': 'Unnamed group',
    'groups.memberCount': '{n} members',
    'groups.membersCount': 'MEMBERS — {n}',
    'groups.members': 'Show member list',
    'groups.owner': 'Group owner',
    'groups.kick': 'Remove from group',
    'groups.kickConfirm': "Remove {name} from the group? The group key is renewed so they can't read new messages.",
    'groups.leave': 'Leave group',
    'groups.leaveConfirm': 'Are you sure you want to leave "{group}"? Its history is deleted from this computer.',
    'groups.addMembers': 'Add friends',
    'groups.add': 'Add',
    'groups.invitePending': 'Invite pending (offline or older version)',
    'groups.messageTo': 'Message {name}',
    'groups.startOfHistory': "This is the beginning of the group. Messages are stored only on members' computers, encrypted.",
    'groups.rename': 'Rename group',
    'groups.renameDesc': 'Every member sees the new name.',
    'groups.startCall': 'Start voice call',
    'groups.join': 'Join',
    'groups.leaveCall': 'Leave',
    'groups.decline': 'Decline',
    'groups.callBy': '{name} started the call',
    'groups.inCall': 'In a call',
    'groups.ringing': 'is calling in {group}…',
    'groups.joiningCall': 'Connecting to the group call…',
    'groups.callGone': 'The call has ended or nobody could be reached.',
    'groups.leaveCurrentTitle': "You're already in a call",
    'groups.leaveCurrentBody': 'Leave the current call and join this group?',
    'groups.deleteMessage': 'Delete message',
    'groups.sendFailed': "Couldn't send the message.",
    'groups.selectFriends': 'SELECT FRIENDS',
    'groups.selectedCount': 'You have selected {n}/{max} friends',
    'groups.searchFriends': 'Type the name of a friend',
    'groups.nameOptional': 'Group name (optional)',
    'groups.create': 'Create Group DM',
    'groups.createDm': 'Create DM',
    'groups.creating': 'Creating…',
    'groups.createFailed': "Couldn't create the group.",
    'groups.noFriends': "You don't have any friends yet.",
    'groups.noMoreFriends': 'No more friends to add.',
    'groups.pendingInvites': '{n} friends are offline or on an older version; they will be invited automatically when they come online.',
    'groups.invitedToast': '{name} added you to "{group}".',
    'groups.removedToast': 'You were removed from "{group}".',
    'groups.keyChanged': "{name}'s security key changed (possibly a reinstall).",
    'groups.sysAdded': '{who} added {target} to the group.',
    'groups.sysRemoved': '{who} removed {target} from the group.',
    'groups.sysLeft': '{who} left the group.',
    'groups.sysRenamed': '{who} renamed the group to "{name}".',
    'groups.sysCall': '{who} started a call.',
    "servers.servers": "Servers",
    "servers.create": "Create a server",
    "servers.createDesc": "Your own community with channels, roles and invite links",
    "servers.join": "Join a server",
    "servers.joinDesc": "With an invite link or code",
    "servers.createTitle": "Create your server",
    "servers.createLead": "Your server is where you and your friends hang out. Pick a name and an icon, then invite your friends.",
    "servers.serverName": "Server name",
    "servers.hostedNote": "The server is hosted on your computer: it's open while you or your chosen co-hosts are online. If none of you are online, it turns grey and read-only.",
    "servers.createBtn": "Create",
    "servers.creating": "Creating…",
    "servers.defaultName": "{name}'s server",
    "servers.defaultText": "general",
    "servers.defaultVoice": "General",
    "servers.upload": "Upload",
    "servers.removeIcon": "Remove icon",
    "servers.iconError": "This image can't be used. Try PNG, JPG or WEBP.",
    "servers.joinTitle": "Join a server",
    "servers.joinLead": "Enter an invite link or code below.",
    "servers.inviteLink": "Invite link",
    "servers.joinExamples": "Invites look like:",
    "servers.joinBtn": "Join server",
    "servers.joining": "Joining…",
    "servers.joinShort": "Join",
    "servers.joined": "Joined",
    "servers.open": "Open",
    "servers.joinedToast": "You joined \"{name}\"!",
    "servers.inviteBadFormat": "That doesn't look like a TeamSync invite link.",
    "servers.inviteLooking": "Looking for the server…",
    "servers.inviteNotFound": "Invite not found: it may have expired, or nobody hosting the server is online right now.",
    "servers.inviteCardLabel": "You've been invited to join a server",
    "servers.inviteLoading": "Loading invite…",
    "servers.inviteInvalid": "Invalid invite",
    "servers.inviteInvalidDesc": "It expired or the server is offline right now.",
    "servers.onlineCount": "{n} online",
    "servers.memberCount": "{n} members",
    "servers.inviteTitle": "Invite friends to {name}",
    "servers.searchFriends": "Search for friends",
    "servers.inviteBtn": "Invite",
    "servers.invited": "Sent",
    "servers.noFriendsToInvite": "No friends to invite.",
    "servers.orSendLink": "Or send a friend an invite link",
    "servers.creatingInvite": "Creating link…",
    "servers.copy": "Copy",
    "servers.copied": "Copied",
    "servers.editInvite": "Edit invite link",
    "servers.expireAfter": "Expire after",
    "servers.maxUses": "Max number of uses",
    "servers.usesN": "{n} uses",
    "servers.usesUnlimited": "No limit",
    "servers.usesLeft": "{n} uses left",
    "servers.generateLink": "Generate a new link",
    "servers.exp1d": "1 day",
    "servers.exp3d": "3 days",
    "servers.exp7d": "7 days",
    "servers.exp30d": "30 days",
    "servers.expNever": "Never",
    "servers.inviteNeverExpires": "This invite never expires.",
    "servers.inviteExpiresDays": "Your invite link expires in {n} days.",
    "servers.inviteExpiresHours": "Your invite link expires in {n} hours.",
    "servers.invite": "Invite",
    "servers.invitePeople": "Invite people",
    "servers.memberList": "Member list",
    "servers.settings": "Server settings",
    "servers.createChannel": "Create channel",
    "servers.createChannelBtn": "Create channel",
    "servers.editChannel": "Edit channel",
    "servers.hosting": "Hosting",
    "servers.changeNick": "Change nickname",
    "servers.changeNickDesc": "Everyone on this server sees you by this name.",
    "servers.markRead": "Mark as read",
    "servers.leave": "Leave server",
    "servers.leaveConfirm": "Are you sure you want to leave \"{name}\"? You will need an invite to join again.",
    "servers.deleteServer": "Delete server",
    "servers.deleteConfirm": "\"{name}\" will be deleted for everyone. This cannot be undone.",
    "servers.deleteLead": "You're about to delete \"{name}\". All channels and messages are removed from everyone's computer; this cannot be undone.",
    "servers.typeName": "Type the server name to confirm",
    "servers.textChannels": "Text channels",
    "servers.voiceChannels": "Voice channels",
    "servers.noTextChannels": "No text channels",
    "servers.noVoiceChannels": "No voice channels",
    "servers.live": "LIVE",
    "servers.syncing": "Getting server info…",
    "servers.syncingLong": "Getting the server info from a host. If nobody hosting it is online, this finishes when someone comes online.",
    "servers.noChannelsVisible": "There's no text channel you can see.",
    "servers.offlineShort": "offline",
    "servers.offlineTitle": "Server offline",
    "servers.offlineBody": "Nobody hosting this server is online right now. You can read older messages, but you can't send messages or join voice channels.",
    "servers.offlineComposer": "Server offline — you can write when a host comes online",
    "servers.offlineVoice": "Server offline: you can join voice channels once a host is online.",
    "servers.noConnect": "You don't have permission to connect to this voice channel.",
    "servers.noSendPerm": "You don't have permission to send messages in this channel",
    "servers.messageTo": "Message #{name}",
    "servers.welcomeChannel": "Welcome to #{name}!",
    "servers.channelStart": "This is the start of the #{name} channel.",
    "servers.loadOlder": "Load older messages",
    "servers.reply": "Reply",
    "servers.edit": "Edit",
    "servers.edited": "(edited)",
    "servers.editHint": "Enter to save · Esc to cancel",
    "servers.deletedMessage": "Deleted message",
    "servers.deleteMessageConfirm": "Delete this message for everyone? (Hold Shift while clicking to skip this.)",
    "servers.replyingTo": "Replying to {name}",
    "servers.slowOn": "Slow mode: {t}",
    "servers.slowWait": "Slow mode — you can write again in {t}",
    "servers.seconds": "{n}s",
    "servers.minutes": "{n}m",
    "servers.hours": "{n}h",
    "servers.slowOff": "Off",
    "servers.onlineSection": "Online",
    "servers.offlineSection": "Offline",
    "servers.owner": "Server owner",
    "servers.hostBadge": "Host: the server is also kept on this person's computer",
    "servers.memberSince": "Member since {date}",
    "servers.roles": "Roles",
    "servers.noRoles": "No roles",
    "servers.addRole": "Add role",
    "servers.removeRole": "Remove role",
    "servers.sendMessage": "Send message",
    "servers.addFriend": "Add friend",
    "servers.kick": "Kick",
    "servers.kickConfirm": "Kick {name} from the server? They can come back with an invite.",
    "servers.ban": "Ban",
    "servers.banConfirm": "Ban {name} from the server? They can't come back until unbanned. Add a reason if you like.",
    "servers.banReason": "Reason (optional)",
    "servers.bannedBy": "by {name}",
    "servers.unban": "Revoke ban",
    "servers.offerHost": "Make host",
    "servers.offerHostConfirm": "Offer {name} co-hosting? If they accept, the server's full history is also kept on their computer and the server stays open while you're offline.",
    "servers.offerHostSent": "Hosting offer sent to {name}.",
    "servers.hostOfferTitle": "Hosting offer",
    "servers.hostOfferBody": "{name} wants you to also host this server on your computer. If you accept, the server stays open while the owner is offline.",
    "servers.hostOfferToast": "You have a hosting offer for \"{name}\".",
    "servers.accept": "Accept",
    "servers.decline": "Decline",
    "servers.nowHost": "You're now a host of this server. History is downloading in the background.",
    "servers.kickedToast": "You were kicked from \"{name}\".",
    "servers.bannedToast": "You were banned from \"{name}\".",
    "servers.deletedToast": "\"{name}\" was deleted.",
    "servers.errOffline": "The server is offline: nobody hosting it is online.",
    "servers.errPerm": "You don't have permission to do that.",
    "servers.errTimeout": "The host didn't answer. Try again.",
    "servers.errClock": "Your computer's clock looks wrong; fix it and try again.",
    "servers.errInvite": "This invite has expired or reached its use limit.",
    "servers.errBanned": "You're banned from this server.",
    "servers.errNotFound": "Server not found or offline right now.",
    "servers.errOwner": "The owner can't leave the server; you can delete it instead.",
    "servers.errNetwork": "No connection. Try again in a moment.",
    "servers.errGeneric": "Something went wrong.",
    "servers.channelType": "Channel type",
    "servers.kindText": "Text",
    "servers.kindTextDesc": "Send messages, emoji and links",
    "servers.kindVoice": "Voice",
    "servers.kindVoiceDesc": "Talk and share your screen",
    "servers.channelName": "Channel name",
    "servers.newChannelPh": "new-channel",
    "servers.privateChannel": "Private channel",
    "servers.privateChannelDesc": "Only the roles you pick (and you) can see it.",
    "servers.privateNoRoles": "No roles yet: for now only you and admins can see it. You can create roles in server settings.",
    "servers.channelSettings": "Channel settings",
    "servers.channelTopic": "Channel topic",
    "servers.slowMode": "Slow mode",
    "servers.slowModeDesc": "Members can't send another message until this time has passed (except people who can manage messages).",
    "servers.channelPerms": "Channel permissions",
    "servers.channelPermsDesc": "Click each box: / the role's default, ✓ allow, ✕ deny. The @everyone row affects everybody.",
    "servers.permShort.VIEW_CHANNEL": "View",
    "servers.permShort.SEND_MESSAGES": "Send",
    "servers.permShort.ADD_REACTIONS": "React",
    "servers.permShort.MANAGE_MESSAGES": "Manage",
    "servers.permShort.CONNECT": "Connect",
    "servers.allow": "Allowed",
    "servers.deny": "Denied",
    "servers.inherit": "Default",
    "servers.remove": "Remove",
    "servers.addRoleOrMember": "Add a role or member",
    "servers.moveUp": "Up",
    "servers.moveDown": "Down",
    "servers.deleteChannel": "Delete channel",
    "servers.deleteChannelConfirm": "Delete #{name}?",
    "servers.save": "Save changes",
    "servers.saved": "Saved.",
    "servers.reset": "Reset",
    "servers.unsaved": "You have unsaved changes!",
    "servers.unsavedTitle": "Unsaved changes",
    "servers.unsavedBody": "Leave without saving?",
    "servers.tabOverview": "Overview",
    "servers.tabRoles": "Roles",
    "servers.tabMembers": "Members",
    "servers.tabInvites": "Invites",
    "servers.tabBans": "Bans",
    "servers.tabHosting": "Hosting",
    "servers.description": "Description",
    "servers.descriptionPh": "What's your server about?",
    "servers.publicTitle": "Show in Server Discovery",
    "servers.publicDesc": "Anyone can find your server and join without an invite (while a host is online). A permanent public invite is created for this.",
    "servers.rolesLead": "Roles give members permissions and a colour. A higher role can manage the ones below it.",
    "servers.createRole": "Create role",
    "servers.newRole": "new role",
    "servers.roleName": "Role name",
    "servers.roleColor": "Role colour",
    "servers.defaultColor": "Default",
    "servers.roleHoist": "Display members separately",
    "servers.roleHoistDesc": "Online members with this role get their own section in the member list.",
    "servers.roleLocked": "This role is above (or equal to) your highest role, so you can't edit it.",
    "servers.everyoneDesc": "@everyone holds everyone's default permissions on this server.",
    "servers.permissions": "Permissions",
    "servers.deleteRole": "Delete role",
    "servers.deleteRoleConfirm": "Delete the role \"{name}\"?",
    "servers.searchMembers": "Search members",
    "servers.manage": "Manage",
    "servers.invitesLead": "Active invite links. You can revoke your own invites, or everyone's with Manage Server.",
    "servers.createInvite": "Create invite",
    "servers.inviter": "Inviter",
    "servers.inviteCode": "Code",
    "servers.uses": "Uses",
    "servers.expires": "Expires",
    "servers.revoke": "Revoke",
    "servers.noInvites": "No active invites.",
    "servers.publicPill": "Public",
    "servers.noBans": "Nobody is banned.",
    "servers.hostingLead": "The server isn't in one central place; it lives on the hosts' computers. The owner and the co-hosts who accepted the owner's offer keep the full message history, approve new messages and enforce the rules (permissions, slow mode, bans). The server is open while at least one of them is online.",
    "servers.hostingUp": "Server open — {n} host(s) online",
    "servers.hostingDown": "Server closed — no host online",
    "servers.hostingMax": "Up to {n} hosts (including the owner).",
    "servers.hosts": "Hosts",
    "servers.ownerHost": "Owner",
    "servers.coHost": "Co-host",
    "servers.onlineNow": "online",
    "servers.offlineNow": "offline",
    "servers.removeHost": "Remove",
    "servers.resignHost": "Stop hosting",
    "servers.resignConfirm": "Stop hosting this server? The message history stays on your computer, but you'll no longer keep the server open.",
    "servers.offerPending": "Offer pending",
    "servers.cancelOffer": "Withdraw offer",
    "servers.pickMember": "Pick a member…",
    "servers.thisComputer": "This computer",
    "servers.storageHost": "As a host, this computer keeps {n} messages (about {mb} MB).",
    "servers.storageMember": "As a member, only the messages you have seen are cached ({n} messages).",
    "servers.discoverTitle": "Server Discovery",
    "servers.discoverLead": "Public TeamSync communities. Only servers with a host online right now are listed.",
    "servers.discoverSearch": "Search communities",
    "servers.discoverLoading": "Looking for public servers…",
    "servers.discoverEmpty": "No public server is online right now.",
    "servers.discoverNoMatch": "No server matches your search.",
    "servers.refresh": "Refresh",
    "servers.haveInvite": "I have an invite",
    "servers.perm.VIEW_CHANNEL": "View channels",
    "servers.permDesc.VIEW_CHANNEL": "Lets members see channels (except private ones).",
    "servers.perm.SEND_MESSAGES": "Send messages",
    "servers.permDesc.SEND_MESSAGES": "Can write in text channels.",
    "servers.perm.ADD_REACTIONS": "Add reactions",
    "servers.permDesc.ADD_REACTIONS": "Can add emoji reactions to messages.",
    "servers.perm.CONNECT": "Connect to voice",
    "servers.permDesc.CONNECT": "Can join and talk in voice channels.",
    "servers.perm.CREATE_INVITE": "Create invite",
    "servers.permDesc.CREATE_INVITE": "Can invite new people to the server.",
    "servers.perm.MANAGE_MESSAGES": "Manage messages",
    "servers.permDesc.MANAGE_MESSAGES": "Can delete other people's messages; not affected by slow mode.",
    "servers.perm.MANAGE_CHANNELS": "Manage channels",
    "servers.permDesc.MANAGE_CHANNELS": "Can create, edit and delete channels and set slow mode.",
    "servers.perm.MANAGE_ROLES": "Manage roles",
    "servers.permDesc.MANAGE_ROLES": "Can edit and assign roles below their highest role, and change channel permissions.",
    "servers.perm.KICK_MEMBERS": "Kick members",
    "servers.permDesc.KICK_MEMBERS": "Can kick members with a lower role.",
    "servers.perm.BAN_MEMBERS": "Ban members",
    "servers.permDesc.BAN_MEMBERS": "Can ban members with a lower role and revoke bans.",
    "servers.perm.MANAGE_SERVER": "Manage server",
    "servers.permDesc.MANAGE_SERVER": "Can change the server's name, icon and description, ping @everyone and revoke any invite.",
    "servers.perm.ADMINISTRATOR": "Administrator",
    "servers.permDesc.ADMINISTRATOR": "Every permission, and bypasses channel restrictions. Grant carefully!",
    "servers.memberCountOne": "{n} member",
    "servers.readOnly": "read-only"
  }
};
