// Discord tarzı kabuk (sunucu rayı, DM sütunu, kullanıcı paneli), durum
// sistemi, profil kartı ve oyun etkinliği metinleri.
// renderer.js bunları I18N.tr / I18N.en'e (ve katalog dillerine İngilizce
// yedek olarak) katar; yeni metin eklerken LEGACY_TEXT_EN'e DOKUNMA — yapısal
// anahtarlar data-i18n / t() ile kullanılır.
window.TeamSyncExtraStrings = {
  tr: {
    'shell.home': 'Direkt Mesajlar',
    'shell.activeCall': 'Aktif arama',
    'shell.addServer': 'Sunucu ekle',
    'shell.searchServers': 'Sunucu keşfet',
    'shell.findChat': 'Sohbet bul ya da başlat',
    'shell.friends': 'Arkadaşlar',
    'shell.directMessages': 'DİREKT MESAJLAR',
    'shell.newDm': 'DM oluştur',
    'shell.voiceConnected': 'Ses Bağlandı',
    'shell.disconnect': 'Bağlantıyı kes',
    'shell.openCall': 'Aramaya dön',
    'shell.mute': 'Sustur',
    'shell.unmute': 'Sesi aç',
    'shell.deafen': 'Sağırlaştır',
    'shell.undeafen': 'Sağırlaştırmayı kaldır',
    'shell.userSettings': 'Kullanıcı Ayarları',
    'shell.closeDm': 'DM’yi kapat',
    'shell.noDms': 'Henüz direkt mesaj yok. Bir arkadaşına yaz!',
    'shell.quickCall': 'Hızlı Arama',
    'shell.quickCallCreate': 'Hızlı arama başlat',
    'shell.quickCallCreateDesc': 'ID ve şifreyle katılınan klasik oda kur',
    'shell.quickCallJoin': 'ID ile katıl',
    'shell.quickCallJoinDesc': 'Bir arkadaşının oda ID’siyle bağlan',
    'shell.serversSoon': 'Sunucular yakında',
    'shell.serversSoonDesc': 'Kanallar, roller ve davet bağlantılı kalıcı sunucular bir sonraki aşamada geliyor.',
    'shell.searchSoon': 'Sunucu keşfi, kalıcı sunucularla birlikte gelecek.',
    'shell.switcherPlaceholder': 'Nereye gitmek istersin?',
    'shell.switcherEmpty': 'Eşleşen sohbet yok.',
    'shell.menu': 'Menü',
    'shell.youInCall': 'Şu an bir aramadasın',
    'friends.online': 'Çevrimiçi',
    'friends.all': 'Tümü',
    'friends.pending': 'Bekleyen',
    'friends.blocked': 'Engellenen',
    'friends.addFriend': 'Arkadaş Ekle',
    'friends.search': 'Ara',
    'friends.countOnline': 'ÇEVRİMİÇİ — {n}',
    'friends.countAll': 'TÜM ARKADAŞLAR — {n}',
    'friends.countBlocked': 'ENGELLENEN — {n}',
    'friends.countPending': 'BEKLEYEN — {n}',
    'friends.emptyOnline': 'Şu an çevrimiçi arkadaşın yok. Biraz bekle, gelirler!',
    'friends.emptyAll': 'Henüz hiç arkadaşın yok.',
    'friends.emptyBlocked': 'Engellediğin kimse yok.',
    'friends.emptyPending': 'Bekleyen arkadaşlık isteği yok.',
    'friends.emptySearch': 'Bu isimde bir arkadaş bulunamadı.',
    'friends.incoming': 'Gelen arkadaşlık isteği',
    'friends.outgoing': 'Giden arkadaşlık isteği',
    'friends.accept': 'Kabul et',
    'friends.reject': 'Reddet',
    'friends.cancelRequest': 'İsteği iptal et',
    'friends.addTitle': 'ARKADAŞ EKLE',
    'friends.addLead': 'Arkadaşlarını TeamSync ID’leriyle ekleyebilirsin (KNK-...).',
    'friends.addPlaceholder': 'Arkadaşının ID’sini gir (KNK-...)',
    'friends.yourId': 'Senin ID’n',
    'friends.activeNow': 'Şimdi Aktif',
    'friends.activeNowEmpty': 'Şimdilik sessiz...',
    'friends.activeNowDesc': 'Bir arkadaşın oyun oynamaya ya da sesli sohbete başladığında burada göreceksin.',
    'friends.inVoice': 'Sesli sohbette',
    'friends.message': 'Mesaj',
    'friends.joinRoom': 'Aramasına katıl',
    'friends.errorValidId': 'Geçerli bir ID gir (kendi ID’n olamaz).',
    'friends.errorAlreadyFriend': 'Bu kişi zaten arkadaşın.',
    'friends.requestSentTo': '{id} kişisine arkadaşlık isteği gönderildi.',
    'dm.startOfHistory': 'Bu, {name} ile olan direkt mesaj geçmişinin başlangıcı.',
    'dm.noMessages': 'Henüz mesaj yok. İlk mesajı sen gönder!',
    'dm.today': 'Bugün',
    'dm.yesterday': 'Dün',
    'dm.messageTo': '@{name} kullanıcısına mesaj gönder',
    'dm.toggleProfile': 'Kullanıcı profilini göster',
    'dm.me': 'Sen',
    'call.chat': 'Sohbet',
    'call.people': 'Kişiler',
    'call.toggleChat': 'Sohbeti göster',
    'call.inviteTitle': 'Aramaya birini davet et',
    'call.inviteDesc': 'Arkadaşlarına davet gönder ya da oda ID’sini paylaş.',
    'call.alone': 'Burada yalnızsın',
    'call.live': 'CANLI',
    'status.online': 'Çevrimiçi',
    'status.idle': 'Boşta',
    'status.dnd': 'Rahatsız Etmeyin',
    'status.invisible': 'Görünmez',
    'status.offline': 'Çevrimdışı',
    'status.onlineShort': 'Aktif',
    'status.dndDesc': 'Masaüstü bildirimleri almayacaksın',
    'status.invisibleDesc': 'Çevrimdışı görüneceksin',
    'status.for15m': '15 Dakika',
    'status.for1h': '1 Saat',
    'status.for8h': '8 Saat',
    'status.for24h': '24 Saat',
    'status.for3d': '3 gün boyunca',
    'status.forever': 'Her Zaman',
    'status.until': '{time} saatine kadar',
    'status.setCustom': 'Özel durum ayarla',
    'status.editCustom': 'Özel durumu düzenle',
    'status.clearCustom': 'Özel durumu temizle',
    'status.customTitle': 'Özel durum ayarla',
    'status.customPlaceholder': 'Neler oluyor?',
    'status.customEmoji': 'Emoji',
    'status.clearAfter': 'Şu süre sonra temizle',
    'status.clear30m': '30 dakika',
    'status.clear1h': '1 saat',
    'status.clear4h': '4 saat',
    'status.clearToday': 'Bugün',
    'status.clearNever': 'Temizleme',
    'status.editProfile': 'Profili Düzenle',
    'status.copyId': 'ID’yi Kopyala',
    'status.switchAccount': 'Hesap Değiştir',
    'status.autoIdle': 'Otomatik boşta',
    'status.idleAfter': 'Şu süre hareketsiz kalınca "Boşta" ol',
    'profile.aboutMe': 'Hakkımda',
    'profile.memberSince': 'TeamSync üyesi',
    'profile.playing': 'Oynuyor',
    'profile.inVoice': 'Sesli sohbette',
    'profile.sendMessage': 'Mesaj Gönder',
    'profile.removeFriend': 'Arkadaşlıktan Çıkar',
    'profile.mute': 'Sessize Al',
    'profile.unmute': 'Sesi Aç',
    'profile.addFriend': 'Arkadaş Ekle',
    'profile.editProfile': 'Profili Düzenle',
    'profile.loading': 'Profil yükleniyor…',
    'profile.settingsNav': 'Profil',
    'profile.settingsTitle': 'Profil',
    'profile.settingsLead': 'Arkadaşlarının profil kartında gördüğü her şeyi buradan özelleştir.',
    'profile.preview': 'Önizleme',
    'profile.displayName': 'Görünen ad',
    'profile.editName': 'Düzenle',
    'profile.avatar': 'Profil fotoğrafı',
    'profile.changeAvatar': 'Fotoğrafı değiştir',
    'profile.animatedAvatar': 'Hareketli profil fotoğrafı (GIF)',
    'profile.animatedAvatarDesc': 'En fazla 2 MB. Eski sürüm kullanan arkadaşların ilk kareyi görür.',
    'profile.uploadGif': 'GIF yükle',
    'profile.remove': 'Kaldır',
    'profile.avatarColor': 'Profil rengi',
    'profile.banner': 'Profil arka planı',
    'profile.bannerDesc': 'Bir renk seç ya da resim/GIF yükle (en fazla 4 MB).',
    'profile.bannerColor': 'Arka plan rengi',
    'profile.uploadBanner': 'Resim / GIF yükle',
    'profile.frame': 'Avatar çerçevesi',
    'profile.frameNone': 'Yok',
    'profile.frameNeon': 'Neon',
    'profile.frameGold': 'Altın',
    'profile.frameRainbow': 'Gökkuşağı',
    'profile.frameFlame': 'Alev',
    'profile.frameFrost': 'Buz',
    'profile.bio': 'Hakkımda',
    'profile.bioPlaceholder': 'Kendinden biraz bahset…',
    'profile.accent': 'Vurgu rengi',
    'profile.typingVerb': 'Yazıyor efekti',
    'profile.typingVerbDesc': 'Arkadaşların sen yazarken "Lazel yazıyor..." yerine bunu görecek. Emoji kullanabilirsin.',
    'profile.typingVerbPlaceholder': 'yazıyor',
    'profile.typingPreview': '{name} {verb}...',
    'profile.unsaved': 'Dikkat — kaydedilmemiş değişikliklerin var!',
    'profile.reset': 'Sıfırla',
    'profile.saveChanges': 'Değişiklikleri Kaydet',
    'profile.saved': 'Profil kaydedildi.',
    'profile.uploadFailed': 'Yükleme başarısız. Supabase kurulumu eksik olabilir (supabase/profile_media.sql).',
    'profile.fileTooLarge': 'Dosya çok büyük.',
    'profile.gifOnly': 'Yalnızca GIF dosyası seçebilirsin.',
    'profile.imageOnly': 'Yalnızca resim dosyası seçebilirsin.',
    'activity.settingsNav': 'Oyun Etkinliği',
    'activity.settingsTitle': 'Oyun Etkinliği',
    'activity.settingsLead': 'TeamSync hangi oyunu oynadığını otomatik algılar ve arkadaşlarına süresiyle birlikte gösterir.',
    'activity.enable': 'Oynadığım oyunu durum olarak göster',
    'activity.enableDesc': 'Kapalıyken algılama tamamen durur. Yalnızca oyunun adı ve süresi paylaşılır; çalışan programların listesi bilgisayarından asla çıkmaz.',
    'activity.current': 'Şu an algılanan',
    'activity.none': 'Algılanan oyun yok',
    'activity.noneDesc': 'Steam, Epic ve popüler oyunlar otomatik tanınır. Tanınmayan bir oyunu aşağıdan ekleyebilirsin.',
    'activity.registered': 'Eklenen oyunlar',
    'activity.registeredEmpty': 'Henüz elle eklenmiş oyun yok.',
    'activity.add': 'Ekle!',
    'activity.addTitle': 'Çalışan bir programı oyun olarak ekle',
    'activity.addPick': 'Program seç…',
    'activity.addName': 'Görünecek ad',
    'activity.rescan': 'Kütüphaneyi yeniden tara',
    'activity.rescanning': 'Taranıyor…',
    'activity.rescanDone': 'Oyun kütüphanesi tarandı: {n} oyun bulundu.',
    'activity.hide': 'Gizle',
    'activity.show': 'Göster',
    'activity.removeGame': 'Kaldır',
    'activity.playingFor': '{time} süredir',
    'activity.sourceSteam': 'Steam',
    'activity.sourceEpic': 'Epic Games',
    'activity.sourceKnown': 'Tanınan oyun',
    'activity.sourceCustom': 'Elle eklendi',
    'activity.unavailable': 'Oyun algılama bu sürümde kullanılamıyor.',
    'activity.playingLine': 'Oynuyor: {name}',
    'typing.default': 'yazıyor',
    'typing.more': 've {n} kişi daha',
    'emoji.matching': ':{q} ile eşleşen emojiler',
    'emoji.search': 'Emoji ara',
    'emoji.picker': 'Emoji',
    'emoji.addReaction': 'Tepki ekle',
    'dm.pending': 'Gönderiliyor — arkadaşın çevrimiçi olunca iletilecek',
    'groups.untitled': 'Adsız grup',
    'groups.memberCount': '{n} üye',
    'groups.membersCount': 'ÜYELER — {n}',
    'groups.members': 'Üye listesini göster',
    'groups.owner': 'Grup sahibi',
    'groups.kick': 'Gruptan çıkar',
    'groups.kickConfirm': '{name} gruptan çıkarılsın mı? Grup anahtarı yenilenir, yeni mesajları göremez.',
    'groups.leave': 'Gruptan ayrıl',
    'groups.leaveConfirm': '"{group}" grubundan ayrılmak istediğine emin misin? Geçmiş bu bilgisayardan silinir.',
    'groups.addMembers': 'Arkadaş ekle',
    'groups.add': 'Ekle',
    'groups.invitePending': 'Davet bekliyor (çevrimdışı ya da eski sürüm)',
    'groups.messageTo': '{name} grubuna mesaj gönder',
    'groups.startOfHistory': 'Grubun başlangıcı. Mesajlar yalnızca üyelerin bilgisayarlarında, şifreli olarak saklanır.',
    'groups.rename': 'Grubun adını değiştir',
    'groups.renameDesc': 'Tüm üyeler yeni adı görür.',
    'groups.startCall': 'Sesli arama başlat',
    'groups.join': 'Katıl',
    'groups.leaveCall': 'Ayrıl',
    'groups.decline': 'Reddet',
    'groups.callBy': '{name} aramayı başlattı',
    'groups.inCall': 'Aramada',
    'groups.ringing': '{group} grubunda arıyor…',
    'groups.joiningCall': 'Grup aramasına bağlanılıyor…',
    'groups.callGone': 'Arama bitmiş ya da kimseye ulaşılamadı.',
    'groups.leaveCurrentTitle': 'Başka bir aramadasın',
    'groups.leaveCurrentBody': 'Mevcut aramadan ayrılıp bu gruba katılmak ister misin?',
    'groups.deleteMessage': 'Mesajı sil',
    'groups.sendFailed': 'Mesaj gönderilemedi.',
    'groups.selectFriends': 'ARKADAŞLARINI SEÇ',
    'groups.selectedCount': '{n}/{max} arkadaş seçildi',
    'groups.searchFriends': 'Bir arkadaşının adını yaz',
    'groups.nameOptional': 'Grup adı (isteğe bağlı)',
    'groups.create': 'Grup DM oluştur',
    'groups.createDm': 'DM oluştur',
    'groups.creating': 'Oluşturuluyor…',
    'groups.createFailed': 'Grup oluşturulamadı.',
    'groups.noFriends': 'Henüz arkadaşın yok.',
    'groups.noMoreFriends': 'Eklenecek başka arkadaşın yok.',
    'groups.pendingInvites': '{n} arkadaşın çevrimdışı ya da eski sürümde; çevrimiçi olunca otomatik davet edilecek.',
    'groups.invitedToast': '{name} seni "{group}" grubuna ekledi.',
    'groups.removedToast': '"{group}" grubundan çıkarıldın.',
    'groups.keyChanged': '{name} kişisinin güvenlik anahtarı değişti (yeniden kurulum olabilir).',
    'groups.sysAdded': '{who}, {target} kişisini gruba ekledi.',
    'groups.sysRemoved': '{who}, {target} kişisini gruptan çıkardı.',
    'groups.sysLeft': '{who} gruptan ayrıldı.',
    'groups.sysRenamed': '{who} grubun adını "{name}" yaptı.',
    'groups.sysCall': '{who} bir arama başlattı.'
  },
  en: {
    'shell.home': 'Direct Messages',
    'shell.activeCall': 'Active call',
    'shell.addServer': 'Add a server',
    'shell.searchServers': 'Discover servers',
    'shell.findChat': 'Find or start a conversation',
    'shell.friends': 'Friends',
    'shell.directMessages': 'DIRECT MESSAGES',
    'shell.newDm': 'Create DM',
    'shell.voiceConnected': 'Voice Connected',
    'shell.disconnect': 'Disconnect',
    'shell.openCall': 'Back to call',
    'shell.mute': 'Mute',
    'shell.unmute': 'Unmute',
    'shell.deafen': 'Deafen',
    'shell.undeafen': 'Undeafen',
    'shell.userSettings': 'User Settings',
    'shell.closeDm': 'Close DM',
    'shell.noDms': 'No direct messages yet. Say hi to a friend!',
    'shell.quickCall': 'Quick Call',
    'shell.quickCallCreate': 'Start a quick call',
    'shell.quickCallCreateDesc': 'Classic room joined with an ID and password',
    'shell.quickCallJoin': 'Join with an ID',
    'shell.quickCallJoinDesc': "Connect using a friend's room ID",
    'shell.serversSoon': 'Servers are coming',
    'shell.serversSoonDesc': 'Persistent servers with channels, roles and invite links arrive in the next phase.',
    'shell.searchSoon': 'Server discovery arrives together with persistent servers.',
    'shell.switcherPlaceholder': 'Where would you like to go?',
    'shell.switcherEmpty': 'No matching conversations.',
    'shell.menu': 'Menu',
    'shell.youInCall': "You're in a call",
    'friends.online': 'Online',
    'friends.all': 'All',
    'friends.pending': 'Pending',
    'friends.blocked': 'Blocked',
    'friends.addFriend': 'Add Friend',
    'friends.search': 'Search',
    'friends.countOnline': 'ONLINE — {n}',
    'friends.countAll': 'ALL FRIENDS — {n}',
    'friends.countBlocked': 'BLOCKED — {n}',
    'friends.countPending': 'PENDING — {n}',
    'friends.emptyOnline': "No one's around to play with right now.",
    'friends.emptyAll': "You don't have any friends yet.",
    'friends.emptyBlocked': "You haven't blocked anyone.",
    'friends.emptyPending': 'There are no pending friend requests.',
    'friends.emptySearch': 'No friends match that name.',
    'friends.incoming': 'Incoming friend request',
    'friends.outgoing': 'Outgoing friend request',
    'friends.accept': 'Accept',
    'friends.reject': 'Ignore',
    'friends.cancelRequest': 'Cancel request',
    'friends.addTitle': 'ADD FRIEND',
    'friends.addLead': 'You can add friends with their TeamSync ID (KNK-...).',
    'friends.addPlaceholder': "Enter your friend's ID (KNK-...)",
    'friends.yourId': 'Your ID',
    'friends.activeNow': 'Active Now',
    'friends.activeNowEmpty': "It's quiet for now...",
    'friends.activeNowDesc': 'When a friend starts playing a game or joins a voice chat, it will show up here.',
    'friends.inVoice': 'In a voice chat',
    'friends.message': 'Message',
    'friends.joinRoom': 'Join their call',
    'friends.errorValidId': "Enter a valid ID (it can't be your own).",
    'friends.errorAlreadyFriend': "You're already friends with this person.",
    'friends.requestSentTo': 'Friend request sent to {id}.',
    'dm.startOfHistory': 'This is the beginning of your direct message history with {name}.',
    'dm.noMessages': 'No messages yet. Send the first one!',
    'dm.today': 'Today',
    'dm.yesterday': 'Yesterday',
    'dm.messageTo': 'Message @{name}',
    'dm.toggleProfile': 'Show user profile',
    'dm.me': 'You',
    'call.chat': 'Chat',
    'call.people': 'People',
    'call.toggleChat': 'Show chat',
    'call.inviteTitle': 'Invite someone to the call',
    'call.inviteDesc': 'Send an invite to friends or share the room ID.',
    'call.alone': "You're alone here",
    'call.live': 'LIVE',
    'status.online': 'Online',
    'status.idle': 'Idle',
    'status.dnd': 'Do Not Disturb',
    'status.invisible': 'Invisible',
    'status.offline': 'Offline',
    'status.onlineShort': 'Online',
    'status.dndDesc': "You won't receive desktop notifications",
    'status.invisibleDesc': "You'll appear offline",
    'status.for15m': 'For 15 Minutes',
    'status.for1h': 'For 1 Hour',
    'status.for8h': 'For 8 Hours',
    'status.for24h': 'For 24 Hours',
    'status.for3d': 'For 3 Days',
    'status.forever': 'Forever',
    'status.until': 'Until {time}',
    'status.setCustom': 'Set Custom Status',
    'status.editCustom': 'Edit Custom Status',
    'status.clearCustom': 'Clear Custom Status',
    'status.customTitle': 'Set a custom status',
    'status.customPlaceholder': "What's happening?",
    'status.customEmoji': 'Emoji',
    'status.clearAfter': 'Clear after',
    'status.clear30m': '30 minutes',
    'status.clear1h': '1 hour',
    'status.clear4h': '4 hours',
    'status.clearToday': 'Today',
    'status.clearNever': "Don't clear",
    'status.editProfile': 'Edit Profile',
    'status.copyId': 'Copy ID',
    'status.switchAccount': 'Switch Account',
    'status.autoIdle': 'Automatic idle',
    'status.idleAfter': 'Become "Idle" after being inactive for',
    'profile.aboutMe': 'About Me',
    'profile.memberSince': 'TeamSync member',
    'profile.playing': 'Playing',
    'profile.inVoice': 'In a voice chat',
    'profile.sendMessage': 'Send Message',
    'profile.removeFriend': 'Remove Friend',
    'profile.mute': 'Mute',
    'profile.unmute': 'Unmute',
    'profile.addFriend': 'Add Friend',
    'profile.editProfile': 'Edit Profile',
    'profile.loading': 'Loading profile…',
    'profile.settingsNav': 'Profile',
    'profile.settingsTitle': 'Profile',
    'profile.settingsLead': "Customize everything your friends see on your profile card.",
    'profile.preview': 'Preview',
    'profile.displayName': 'Display name',
    'profile.editName': 'Edit',
    'profile.avatar': 'Avatar',
    'profile.changeAvatar': 'Change avatar',
    'profile.animatedAvatar': 'Animated avatar (GIF)',
    'profile.animatedAvatarDesc': 'Up to 2 MB. Friends on older versions see the first frame.',
    'profile.uploadGif': 'Upload GIF',
    'profile.remove': 'Remove',
    'profile.avatarColor': 'Profile color',
    'profile.banner': 'Profile banner',
    'profile.bannerDesc': 'Pick a color or upload an image/GIF (up to 4 MB).',
    'profile.bannerColor': 'Banner color',
    'profile.uploadBanner': 'Upload image / GIF',
    'profile.frame': 'Avatar frame',
    'profile.frameNone': 'None',
    'profile.frameNeon': 'Neon',
    'profile.frameGold': 'Gold',
    'profile.frameRainbow': 'Rainbow',
    'profile.frameFlame': 'Flame',
    'profile.frameFrost': 'Frost',
    'profile.bio': 'About Me',
    'profile.bioPlaceholder': 'Tell people a little about yourself…',
    'profile.accent': 'Accent color',
    'profile.typingVerb': 'Typing effect',
    'profile.typingVerbDesc': 'Friends will see this instead of "Lazel is typing..." while you type. Emoji allowed.',
    'profile.typingVerbPlaceholder': 'is typing',
    'profile.typingPreview': '{name} {verb}...',
    'profile.unsaved': 'Careful — you have unsaved changes!',
    'profile.reset': 'Reset',
    'profile.saveChanges': 'Save Changes',
    'profile.saved': 'Profile saved.',
    'profile.uploadFailed': 'Upload failed. The Supabase setup may be missing (supabase/profile_media.sql).',
    'profile.fileTooLarge': 'That file is too large.',
    'profile.gifOnly': 'Please choose a GIF file.',
    'profile.imageOnly': 'Please choose an image file.',
    'activity.settingsNav': 'Activity',
    'activity.settingsTitle': 'Game Activity',
    'activity.settingsLead': 'TeamSync detects which game you are playing and shows it to your friends with a timer.',
    'activity.enable': 'Display current activity as a status message',
    'activity.enableDesc': 'When off, detection stops completely. Only the game name and play time are shared; your list of running programs never leaves your PC.',
    'activity.current': 'Currently detected',
    'activity.none': 'No game detected',
    'activity.noneDesc': "Steam, Epic and popular games are recognized automatically. Add a game that isn't recognized below.",
    'activity.registered': 'Added games',
    'activity.registeredEmpty': 'No manually added games yet.',
    'activity.add': 'Add it!',
    'activity.addTitle': 'Add a running program as a game',
    'activity.addPick': 'Select a program…',
    'activity.addName': 'Display name',
    'activity.rescan': 'Rescan game library',
    'activity.rescanning': 'Scanning…',
    'activity.rescanDone': 'Game library scanned: {n} games found.',
    'activity.hide': 'Hide',
    'activity.show': 'Show',
    'activity.removeGame': 'Remove',
    'activity.playingFor': 'for {time}',
    'activity.sourceSteam': 'Steam',
    'activity.sourceEpic': 'Epic Games',
    'activity.sourceKnown': 'Recognized game',
    'activity.sourceCustom': 'Added manually',
    'activity.unavailable': 'Game detection is not available in this build.',
    'activity.playingLine': 'Playing {name}',
    'typing.default': 'is typing',
    'typing.more': 'and {n} more',
    'emoji.matching': 'Emoji matching :{q}',
    'emoji.search': 'Search emoji',
    'emoji.picker': 'Emoji',
    'emoji.addReaction': 'Add reaction',
    'dm.pending': "Sending — will be delivered when your friend is online",
    'groups.untitled': 'Unnamed group',
    'groups.memberCount': '{n} members',
    'groups.membersCount': 'MEMBERS — {n}',
    'groups.members': 'Show member list',
    'groups.owner': 'Group owner',
    'groups.kick': 'Remove from group',
    'groups.kickConfirm': "Remove {name} from the group? The group key is renewed so they can't read new messages.",
    'groups.leave': 'Leave group',
    'groups.leaveConfirm': 'Are you sure you want to leave "{group}"? Its history is deleted from this computer.',
    'groups.addMembers': 'Add friends',
    'groups.add': 'Add',
    'groups.invitePending': 'Invite pending (offline or older version)',
    'groups.messageTo': 'Message {name}',
    'groups.startOfHistory': "This is the beginning of the group. Messages are stored only on members' computers, encrypted.",
    'groups.rename': 'Rename group',
    'groups.renameDesc': 'Every member sees the new name.',
    'groups.startCall': 'Start voice call',
    'groups.join': 'Join',
    'groups.leaveCall': 'Leave',
    'groups.decline': 'Decline',
    'groups.callBy': '{name} started the call',
    'groups.inCall': 'In a call',
    'groups.ringing': 'is calling in {group}…',
    'groups.joiningCall': 'Connecting to the group call…',
    'groups.callGone': 'The call has ended or nobody could be reached.',
    'groups.leaveCurrentTitle': "You're already in a call",
    'groups.leaveCurrentBody': 'Leave the current call and join this group?',
    'groups.deleteMessage': 'Delete message',
    'groups.sendFailed': "Couldn't send the message.",
    'groups.selectFriends': 'SELECT FRIENDS',
    'groups.selectedCount': 'You have selected {n}/{max} friends',
    'groups.searchFriends': 'Type the name of a friend',
    'groups.nameOptional': 'Group name (optional)',
    'groups.create': 'Create Group DM',
    'groups.createDm': 'Create DM',
    'groups.creating': 'Creating…',
    'groups.createFailed': "Couldn't create the group.",
    'groups.noFriends': "You don't have any friends yet.",
    'groups.noMoreFriends': 'No more friends to add.',
    'groups.pendingInvites': '{n} friends are offline or on an older version; they will be invited automatically when they come online.',
    'groups.invitedToast': '{name} added you to "{group}".',
    'groups.removedToast': 'You were removed from "{group}".',
    'groups.keyChanged': "{name}'s security key changed (possibly a reinstall).",
    'groups.sysAdded': '{who} added {target} to the group.',
    'groups.sysRemoved': '{who} removed {target} from the group.',
    'groups.sysLeft': '{who} left the group.',
    'groups.sysRenamed': '{who} renamed the group to "{name}".',
    'groups.sysCall': '{who} started a call.'
  }
};
